### ISSUE TITLE
savePdf

### ISSUE THREAD

**Issue by zygimantus** [375670450/JPDFViewer#1]
How do you actually save PDFs with this library?

Doing this:

```java
PDFSource pdfs = new FilePDFSource("someFile.pdf");
notesBean.loadPDF(pdfs);

// doing changes to file here...

notesBean.commitEdits();
notesBean.save();
```

Results to this error:

> 
> java.lang.VerifyError: Instruction type does not match stack map
> Exception Details:
>   Location:
>     com/qoppa/pdf/h/i.b(Ljava/io/InputStream;Lcom/qoppa/pdf/n/k;)Ljava/io/InputStream; @39: aload_0
>   Reason:
>     Type 'com/qoppa/pdf/h/q' (current frame, locals[0]) is not assignable to 'java/io/InputStream' (stack map, locals[0])
>   Current Frame:
>     bci: @39
>     flags: { }
>     locals: { 'com/qoppa/pdf/h/q', 'com/qoppa/pdf/n/k', integer }
>     stack: { }
>   Stackmap Frame:
>     bci: @39
>     flags: { }
>     locals: { 'java/io/InputStream', 'com/qoppa/pdf/n/k' }
>     stack: { }
>   Bytecode:
>     0x0000000: bb00 1359 2ab7 0015 4b2b c600 1d2b 1218
>     0x0000010: b600 1a02 b800 203d 1c04 a400 0dbb 0026
>     0x0000020: 592a 2bb7 0028 4b2a b0                 
>   Stackmap Table:
>     same_frame(@39)
> 
> 	at com.qoppa.pdf.n.g.b(Unknown Source)
> 	at com.qoppa.pdf.n.g.tb(Unknown Source)
> 	at com.qoppa.pdf.n.g.sb(Unknown Source)
> 	at com.qoppa.b.h.w(Unknown Source)
> 	at com.qoppa.b.h.b(Unknown Source)
> 	at com.qoppa.b.f.b(Unknown Source)
> 	at com.qoppa.b.d.u.b(Unknown Source)
> 	at com.qoppa.b.c.x(Unknown Source)
> 	at com.qoppa.b.c.c(Unknown Source)
> 	at com.qoppa.b.c.q(Unknown Source)
> 	at com.qoppa.pdfNotes.PDFNotesBean.save(Unknown Source)
> 	at com.qoppa.pdfNotes.PDFNotesBean.save(Unknown Source)

**Comment by stardust95** [comment]
Try to change
`notesBean.save();`
to
`notesBean.saveDocument(filepath);`
